title: [@ReubenSultana]
description: [Born naked, helpless, unable to provide for myself, I nevertheless overcame these obstacles to become a partially productive member of society]

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
